# Generated by Django 5.1.2 on 2024-11-03 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "points_used",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("user_name", models.CharField(default="Anonymous", max_length=255)),
                (
                    "phone_number",
                    models.CharField(default="000-0000-0000", max_length=15),
                ),
                (
                    "shipping_address_detail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "결제 완료"),
                            ("refunded", "환불 완료"),
                            ("failed", "결제 실패"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "신용/체크 카드"),
                            ("transfer", "계좌 이체"),
                            ("kakaopay", "카카오페이"),
                            ("naverpay", "네이버페이"),
                            ("samsungpay", "삼성페이"),
                            ("virtual_account", "가상계좌"),
                            ("mobile", "휴대폰 결제"),
                            ("point", "포인트"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shipping_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_status",
                    models.CharField(
                        choices=[
                            ("preparing", "배송 준비 중"),
                            ("sending", "상품 발송"),
                            ("delivery_company_arrives", "택배사 도착"),
                            ("shipping", "배송 중"),
                            ("delivered", "배송 완료"),
                            ("canceled", "주문 취소"),
                            ("returned", "반품 완료"),
                        ],
                        default="preparing",
                        max_length=30,
                    ),
                ),
                ("shipping_memo", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                (
                    "discount_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("product_id", models.IntegerField()),
                ("product_company", models.CharField(max_length=255)),
                ("product_image", models.URLField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payments.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "결제 완료"),
                            ("refunded", "환불 완료"),
                            ("failed", "결제 실패"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pg_tx_id", models.CharField(max_length=100)),
                ("receipt_url", models.URLField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refund_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("refund_requested_date", models.DateTimeField(auto_now_add=True)),
                ("refund_completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "환불 요청됨"),
                            ("processing", "환불 처리 중"),
                            ("completed", "환불 완료"),
                            ("rejected", "환불 거절"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.transaction",
            ),
        ),
    ]
