# Generated by Django 5.1.2 on 2024-11-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancellation_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "결제 완료"),
                    ("refunded", "환불 완료"),
                    ("failed", "결제 실패"),
                    ("canceled", "주문 취소"),
                ],
                max_length=20,
            ),
        ),
    ]
