# Generated by Django 5.1.2 on 2024-10-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_memo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
