# Generated by Django 5.1.2 on 2024-10-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_order_shipping_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="final_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="original_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
