# Generated by Django 5.1.2 on 2024-10-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_order_final_amount_order_original_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="final_amount",
        ),
    ]
