# Generated by Django 5.1.2 on 2024-10-29 01:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_remove_order_final_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payment",
            new_name="Transaction",
        ),
    ]
