# Generated by Django 5.1.2 on 2024-10-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_rename_payment_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productorder",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
