# Generated by Django 5.1.2 on 2024-10-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_productorder_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productorder",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
