# Generated by Django 5.1.2 on 2024-10-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_alter_productorder_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default="000-0000-0000", max_length=15),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address_detail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="user_name",
            field=models.CharField(default="Anonymous", max_length=255),
        ),
        migrations.AddField(
            model_name="productorder",
            name="discount_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="productorder",
            name="product_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
