# Generated by Django 5.1.2 on 2024-10-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_order_phone_number_order_shipping_address_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="product_company",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
