# Generated by Django 5.1.2 on 2024-11-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_productorder_product_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="product_image",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
