# Generated by Django 5.1.2 on 2024-11-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_productorder_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "결제 완료"),
                    ("refunded", "환불 완료"),
                    ("failed", "결제 실패"),
                ],
                default=0,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
