# Generated by Django 5.1.2 on 2024-10-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_detail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
