# Generated by Django 5.1.2 on 2024-10-23 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatBreedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_id", models.IntegerField(unique=True)),
                ("breed_type", models.CharField(max_length=255, unique=True)),
                ("rank", models.IntegerField(unique=True)),
            ],
            options={
                "db_table": "cat_breed_data",
            },
        ),
        migrations.CreateModel(
            name="CatData",
            fields=[
                ("cat_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("birth_date", models.DateField()),
                ("gender", models.IntegerField(choices=[(0, "여아"), (1, "남아")])),
                (
                    "is_neutered",
                    models.IntegerField(choices=[(0, "안 했어요"), (1, "했어요")]),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "cat_breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.catbreeddata",
                        to_field="category_id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cat_data",
            },
        ),
    ]
