# Generated by Django 5.1.2 on 2024-10-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_catbreed_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="cat_profiles/"),
        ),
        migrations.AlterField(
            model_name="cat",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
