# Generated by Django 5.1.2 on 2024-10-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_cat_profile_image_alter_cat_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="profile_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
