# Generated by Django 5.1.2 on 2024-10-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_address_detail"),
        ("account", "0004_alter_cat_profile_image"),
    ]

    operations = []
