# Generated by Django 5.1.2 on 2024-11-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_merge_20241024_1717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
