# Generated by Django 5.1.2 on 2024-10-29 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_merge_20241024_1717"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="points",
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "point_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("point", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
