# Generated by Django 5.1.2 on 2024-10-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_user_points_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="kakao_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="naver_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
