# Generated by Django 5.1.2 on 2024-11-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_user_phone_number"),
        ("account", "0007_alter_user_google_id_alter_user_kakao_id_and_more"),
    ]

    operations = []
