version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      # 필요한 환경 변수를 설정
      DJANGO_SETTINGS_MODULE: forcatProject.settings
