# Generated by Django 5.1.2 on 2024-10-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
