# Generated by Django 5.1.2 on 2024-10-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="remain_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
