# Generated by Django 5.1.2 on 2024-10-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_thumbnail_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='image_url',
        ),
    ]
